### PR TITLE
Bill with additional private moneys

### PR DESCRIPTION
**Pull request by ZweWaiYanHtet**
### Ref
https://coilinc.slack.com/archives/CSDAE8S05/p1688715876992469

### CODE REVIEW

**Comment by ZweWaiYanHtet** [comment]
@taniryo-kun 
The `Bill` response and the new `BillWithAdditionalMoneys` response is the same except that `BillWithAdditionalMoneys` has one additional field of `PrivateMoney` array.  
I think it might be better to inherit `BillWithAdditionalMoneys` from `Bill` rather creating a separate class.  This can ease the user update process.

`e.g.` : Bill getBill = new GetBill("id").send("access_token")
- there will be an error if create a separate class.  With inheritance, there won't be an error.

**Comment by taniryo-kun** [comment]
@ZweWaiYanHtet sounds good, are you planning to fix the code?

**Comment by ZweWaiYanHtet** [comment]
Yes, I'll fix it.  Let me see if it can be done without changing too much.

**Review by taniryo-kun — APPROVED** [review]
LGTM

**Pull request merged**
